// <auto-generated />
using System;
using DietAndFitness.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DietAndFitness.Migrations
{
    [DbContext(typeof(SQLiteDbContext))]
    partial class SQLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("DietAndFitness.Entities.LocalFoodItem", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<double?>("Calories")
                        .IsRequired();

                    b.Property<double?>("Carbohydrates");

                    b.Property<string>("CookingMode");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("Deleted");

                    b.Property<double?>("Fats");

                    b.Property<string>("GUID");

                    b.Property<bool>("IsDirty");

                    b.Property<DateTime>("ModifiedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double?>("Proteins");

                    b.HasKey("ID");

                    b.HasIndex("GUID")
                        .IsUnique();

                    b.ToTable("LocalFoodItems");
                });
#pragma warning restore 612, 618
        }
    }
}
